services:
  nginx:
    image: nginx:1.27
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: cafe_work_record
      POSTGRES_USER : laravel
      POSTGRES_PASSWORD: xxxxxxxx
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

# 以下のようなコマンドで使用する
# docker compose run --rm node npm install tailwindcss @tailwindcss/vite --save-dev
# docker compose run --rm --service-ports node npm run dev
  node:
    image: node:22
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
volumes:
  postgres-data: