server {
    listen 80;
    server_name azumaki.com cafe-log.azumaki.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        auth_basic off;
    }


    return 301 https://cafe-log.azumaki.com$request_uri;
}

server {
    listen 443 ssl;
    server_name azumaki.com;

    ssl_certificate /etc/letsencrypt/live/cafe-log.azumaki.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cafe-log.azumaki.com/privkey.pem;

    return 301 https://cafe-log.azumaki.com$request_uri;
}

server {
    listen 443 ssl;
    server_name cafe-log.azumaki.com;

    ssl_certificate /etc/letsencrypt/live/cafe-log.azumaki.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cafe-log.azumaki.com/privkey.pem;

    root /var/www/html/public;
    index index.php index.html;

    auth_basic "CafeLog";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        auth_basic off;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

server {
    listen 80;
    server_name offer-note.azumaki.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        auth_basic off;
    }

    return 301 https://offer-note.azumaki.com$request_uri;
}

server {
    listen 443 ssl;
    server_name offer-note.azumaki.com;

    ssl_certificate /etc/letsencrypt/live/offer-note.azumaki.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/offer-note.azumaki.com/privkey.pem;

    auth_basic "OfferNote";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        proxy_pass http://offer-note-app-prod:8080;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
